const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const { spawn } = require('node:child_process');
const { once } = require('node:events');
const fs = require('node:fs/promises');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const port = process.env.TEST_PORT || '8127';
let browser;
const server = spawn(process.execPath, ['scripts/serve.mjs'], { cwd: root, env: { ...process.env, PORT: port }, stdio: ['ignore', 'pipe', 'pipe'] });
const errors = [];
let checks = 0;
const pass = label => { checks++; console.log(`PASS: ${label}`); };
const exportData = page => page.evaluate(() => JSON.parse(localStorage.getItem('readypack.checklist.v1')));
(async () => {
  const startTimeout = setTimeout(() => server.kill(), 10000);
  await Promise.race([once(server.stdout, 'data'), once(server, 'exit').then(() => { throw new Error('Test server exited before startup'); })]);
  clearTimeout(startTimeout);
  browser = await chromium.launch({ headless: true, ...(process.env.CHROME_EXECUTABLE_PATH ? { executablePath: process.env.CHROME_EXECUTABLE_PATH } : {}) });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
  const page = await context.newPage();
  page.setDefaultTimeout(6000);
  page.on('pageerror', error => errors.push(error.message));
  let acceptDialogs = true;
  page.on('dialog', dialog => acceptDialogs ? dialog.accept() : dialog.dismiss());
  await page.goto(`http://127.0.0.1:${port}`);
  await page.locator('#items li').first().waitFor();
  assert.equal(await page.locator('#items li').count(), 8);
  assert.equal(await page.locator('#percent').textContent(), '38%');
  pass('fresh sample and progress');
  await fs.mkdir(path.join(root, 'docs/screenshots'), { recursive: true });
  await page.screenshot({ path: path.join(root, 'docs/screenshots/desktop.png'), fullPage: true });
  await page.getByRole('button', { name: 'Add item' }).click();
  await page.locator('#item-title').fill('   ');
  await page.getByRole('button', { name: 'Save item' }).click();
  assert.equal(await page.locator('#item-dialog').evaluate(node => node.open), true);
  assert.equal(await page.locator('#form-error').isVisible(), true);
  pass('whitespace name rejected');
  await page.locator('#item-title').fill('Travel adapter');
  await page.locator('#item-category').selectOption('Electronics');
  await page.locator('#item-quantity').fill('0');
  await page.getByRole('button', { name: 'Save item' }).click();
  assert.equal(await page.locator('#item-quantity').evaluate(node => node.validity.valid), false);
  pass('invalid quantity rejected');
  await page.locator('#item-quantity').fill('2');
  await page.locator('#item-essential').check();
  await page.getByRole('button', { name: 'Save item' }).click();
  assert.equal(await page.locator('#items li').count(), 9);
  await page.reload();
  await page.getByRole('checkbox', { name: 'Packed: Travel adapter', exact: true }).waitFor();
  pass('add and persistence after reload');
  await page.getByRole('checkbox', { name: 'Packed: Travel adapter', exact: true }).check();
  await page.getByRole('button', { name: 'Edit Travel adapter', exact: true }).click();
  await page.locator('#item-title').fill('Universal adapter');
  await page.locator('#item-quantity').fill('3');
  await page.getByRole('button', { name: 'Save item' }).click();
  assert.equal(await page.getByRole('checkbox', { name: 'Packed: Universal adapter', exact: true }).isChecked(), true);
  assert.equal((await exportData(page)).items.find(item => item.title === 'Universal adapter').quantity, 3);
  pass('edit preserves packed state');
  await page.locator('#categories').getByRole('button', { name: /^Electronics/ }).click();
  await page.locator('#search').fill('adapter');
  await page.locator('#status').selectOption('packed');
  await page.locator('#essential-only').check();
  assert.equal(await page.locator('#items li').count(), 1);
  pass('combined filters');
  await page.getByRole('button', { name: 'Delete Universal adapter', exact: true }).click();
  assert.equal(await page.locator('#items li').count(), 0);
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  assert.equal(await page.locator('#items li').count(), 1);
  pass('delete and undo');
  await page.locator('#search').fill('no-match-here');
  assert.equal(await page.locator('#empty-state').isVisible(), true);
  pass('filtered empty state');
  const exported = await exportData(page);
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export checklist', exact: true }).click();
  const download = await downloadPromise;
  const downloadPath = await download.path();
  assert.deepEqual(JSON.parse(await fs.readFile(downloadPath, 'utf8')), exported);
  pass('export contents');
  await page.locator('#import-file').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{') });
  await page.getByText('Import failed: The file must contain valid JSON.', { exact: true }).waitFor();
  assert.deepEqual(await exportData(page), exported);
  pass('invalid import preserves current list');
  acceptDialogs = false;
  await page.getByRole('button', { name: 'Reset demo', exact: true }).click();
  assert.deepEqual(await exportData(page), exported);
  pass('cancel reset preserves data');
  acceptDialogs = true;
  await page.locator('#import-file').setInputFiles({ name: 'good.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(exported)) });
  await page.getByText('Imported 9 items.', { exact: true }).waitFor();
  assert.equal(await page.locator('#items li').count(), 9);
  pass('import round-trip clears filters');
  const literal = '<img src=x onerror=alert(1)>';
  const injected = { version: 1, items: [{ id: 'markup', title: literal, category: 'Other', quantity: 1, essential: false, packed: false }] };
  await page.locator('#import-file').setInputFiles({ name: 'text.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(injected)) });
  await page.getByText(literal, { exact: true }).waitFor();
  assert.equal(await page.locator('#items img').count(), 0);
  pass('HTML-looking input renders as text');
  await page.getByRole('button', { name: `Delete ${literal}`, exact: true }).click();
  assert.equal(await page.locator('#percent').textContent(), '0%');
  assert.equal(await page.locator('#empty-state').isVisible(), true);
  pass('empty list progress');
  await page.getByRole('button', { name: 'Reset demo', exact: true }).click();
  assert.equal(await page.locator('#items li').count(), 8);
  await page.locator('#status').selectOption('unpacked');
  await page.getByRole('checkbox', { name: 'Packed: Phone charger', exact: true }).click();
  assert.equal(await page.getByRole('checkbox', { name: 'Packed: Phone charger', exact: true }).count(), 0);
  assert.equal(await page.evaluate(() => document.activeElement.id), 'status');
  pass('packing under a filter keeps keyboard focus');
  await page.getByRole('button', { name: 'Reset demo', exact: true }).click();
  await page.getByRole('button', { name: 'Add item' }).click();
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#item-dialog').evaluate(node => node.open), false);
  assert.equal(await page.evaluate(() => document.activeElement.id), 'add-item');
  pass('dialog Escape and focus return');
  await page.getByRole('button', { name: 'Dismiss notification' }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => window.scrollTo(0, 0));
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  await page.screenshot({ path: path.join(root, 'docs/screenshots/mobile.png'), fullPage: true });
  await page.getByRole('button', { name: 'Add item' }).click();
  assert.equal(await page.locator('#item-dialog').evaluate(node => node.getBoundingClientRect().right <= innerWidth), true);
  await page.screenshot({ path: path.join(root, 'docs/screenshots/item-form.png'), fullPage: false });
  pass('mobile layout and form fit');
  const limited = await browser.newContext();
  await limited.addInitScript(() => {
    Storage.prototype.getItem = () => { throw new Error('Storage blocked'); };
    Storage.prototype.setItem = () => { throw new Error('Storage blocked'); };
  });
  const limitedPage = await limited.newPage();
  limitedPage.on('pageerror', error => errors.push(error.message));
  await limitedPage.goto(`http://127.0.0.1:${port}`);
  await limitedPage.locator('#items li').first().waitFor();
  assert.equal(await limitedPage.locator('#storage-warning').isVisible(), true);
  await limitedPage.getByRole('checkbox', { name: 'Packed: Phone charger', exact: true }).check();
  assert.equal(await limitedPage.getByRole('checkbox', { name: 'Packed: Phone charger', exact: true }).isChecked(), true);
  pass('blocked storage remains usable');
  assert.deepEqual(errors, []);
  pass('no browser page exceptions');
  console.log(`${checks} browser workflow checks passed`);
})().catch(error => { console.error(error); process.exitCode = 1; }).finally(async () => {
  if (browser) await browser.close();
  server.kill();
});
