const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const { spawn } = require('node:child_process');
const { once } = require('node:events');
const fs = require('node:fs/promises');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const port = process.env.CHATBOT_TEST_PORT || '8131';
const base = process.env.CHATBOT_TEST_URL || `http://127.0.0.1:${port}/chatbot/`;
const server = process.env.CHATBOT_TEST_URL ? null : spawn(process.execPath, ['scripts/serve.mjs'], { cwd: root, env: { ...process.env, PORT: port }, stdio: ['ignore', 'pipe', 'pipe'] });
let browser; let checks = 0; const errors = []; const requests = [];
const pass = label => { checks++; console.log(`PASS: ${label}`); };
(async () => {
  if (server) {
    await Promise.race([once(server.stdout, 'data'), once(server, 'exit').then(() => { throw Error('Server exited'); }), new Promise((_, reject) => { const timer = setTimeout(() => reject(Error('Startup timeout')), 10000); timer.unref(); })]);
  }
  browser = await chromium.launch({ headless: true, ...(process.env.CHROME_EXECUTABLE_PATH ? { executablePath: process.env.CHROME_EXECUTABLE_PATH } : {}) });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
  const page = await context.newPage(); page.setDefaultTimeout(7000);
  page.on('pageerror', error => errors.push(error.message)); page.on('request', request => requests.push({ url: request.url(), method: request.method(), type: request.resourceType() }));
  const submit = async text => { await page.locator('#request').fill(text); await page.locator('#send').click(); };
  const reset = () => page.locator('#reset').click();
  await page.goto(base); await page.getByRole('heading', { name: 'Your intake guide' }).waitFor();
  assert.match(await page.locator('#mode-status').textContent(), /rules mode/); pass('initial state explains automated local demo');
  await page.getByRole('button', { name: /An inherited property/ }).click();
  await page.getByRole('button', { name: /Estate intake/ }).waitFor();
  assert.equal(await page.locator('.service-card').count(), 2);
  assert.match(await page.locator('#mode-status').textContent(), /replay fixture/); pass('explicit replay presents two validated service cards');
  await fs.mkdir(path.join(root, 'chatbot/docs/screenshots'), { recursive: true });
  await page.screenshot({ path: path.join(root, 'chatbot/docs/screenshots/desktop.png'), fullPage: true });
  await reset(); await submit("I lost my driver's license");
  await page.getByRole('button', { name: /Affidavit intake/ }).click();
  await page.getByRole('button', { name: 'Lost license', exact: true }).click();
  assert.equal(await page.evaluate(() => document.activeElement.id), 'document-0'); pass('keyboard focus follows removed choice into next step');
  await page.getByRole('checkbox', { name: 'Sample statement draft' }).check();
  await page.locator('#documents-form').getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByRole('button', { name: 'Yes, urgent' }).click();
  await page.getByRole('button', { name: 'Email', exact: true }).click();
  assert.match(await page.locator('#intake-summary').textContent(), /Alex Example/);
  assert.match(await page.locator('#intake-summary').textContent(), /Urgent/);
  assert.match(await page.locator('#intake-summary').textContent(), /Sample statement draft/); pass('full English intake produces fictional summary');
  const downloadWait = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export sample summary' }).click();
  const download = await downloadWait; const exported = JSON.parse(await fs.readFile(await download.path(), 'utf8'));
  assert.equal(exported.service, 'Affidavit intake'); assert.equal(exported.urgent, true); assert.equal(exported.simulated, true); assert.equal(exported.preference, 'email'); pass('export preserves selected data and simulation flag');
  await page.getByRole('button', { name: 'Finish demo' }).click(); await page.getByText('✓ Demo complete', { exact: true }).waitFor(); pass('completion does not claim office delivery');
  await page.reload(); assert.equal(await page.locator('#intake-summary').count(), 0); pass('reload clears conversation instead of retaining client data');
  await page.locator('#language').selectOption('es');
  await page.getByRole('button', { name: /Una licencia de conducir perdida/ }).click();
  await page.getByRole('button', { name: /Recepción de declaraciones juradas/ }).click();
  await page.getByRole('button', { name: 'Licencia perdida', exact: true }).click();
  await page.locator('#documents-form').getByRole('button', { name: 'Continuar', exact: true }).click();
  await page.getByRole('button', { name: 'Sin urgencia', exact: true }).click();
  await page.getByRole('button', { name: 'Solicitud de cita', exact: true }).click();
  assert.equal(await page.locator('html').getAttribute('lang'), 'es');
  assert.match(await page.locator('#intake-summary').textContent(), /Entregar después/);
  assert.match(await page.locator('#intake-summary').textContent(), /No se envía una solicitud ni se reserva una cita/); pass('Spanish flow supports deferred documents and appointment preference');
  await page.locator('#language').selectOption('en');
  await submit('unknown'); await submit('hmm'); assert.equal(await page.locator('.service-card').count(), 6); pass('second failed recognition opens catalog');
  await submit('still unclear'); await page.getByText('Team review simulation', { exact: true }).waitFor(); pass('third failure prepares simulated human handoff');
  await reset(); await page.getByRole('button', { name: /An invalid model response/ }).click();
  assert.equal(await page.locator('.service-card').count(), 0); assert.match(await page.locator('#transcript').textContent(), /Is this about a property/); pass('invented model service is rejected and clarification remains usable');
  await reset(); await submit('I was arrested and need help with property');
  await page.getByText('Team review simulation', { exact: true }).waitFor(); assert.equal(await page.locator('.service-card').count(), 0); pass('criminal request overrides service matching');
  await reset(); await submit('<img src=x onerror=alert(1)>');
  assert.equal(await page.locator('#transcript img').count(), 0); assert.match(await page.locator('#transcript').textContent(), /<img src=x/); pass('HTML-like input renders as text');
  await reset(); await page.locator('#browse').click(); await page.getByRole('button', { name: /Family consultation/ }).click();
  await page.getByRole('button', { name: 'Custody', exact: true }).click(); await page.locator('#documents-form').getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByRole('button', { name: 'No urgency', exact: true }).click(); await page.getByRole('button', { name: 'Phone', exact: true }).click();
  assert.match(await page.locator('#intake-summary').textContent(), /Custody/); pass('catalog selection can complete without free-text recognition');
  await reset(); await page.locator('#human').click(); await page.getByText('Team review simulation', { exact: true }).waitFor(); pass('direct team-review control works');
  await reset(); await page.locator('#language').selectOption('es'); await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: /Una propiedad heredada/ }).click();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: path.join(root, 'chatbot/docs/screenshots/mobile.png'), fullPage: true }); pass('390px Spanish layout fits viewport');
  assert.equal(requests.some(request => ['fetch', 'xhr'].includes(request.type)), false);
  assert.equal(requests.some(request => request.method !== 'GET'), false); pass('flows make no model, upload, or submission requests');
  assert.deepEqual(errors, []); pass('no browser page exceptions');
  console.log(`${checks} chatbot browser workflow checks passed`);
})().catch(error => { console.error(error); process.exitCode = 1; }).finally(async () => { if (browser) await browser.close(); if (server) server.kill(); });
