// Fictional demonstration catalog; no private office data.
export const SERVICES = [
  { id: 'property', name: { en: 'Property document review', es: 'Revisión de documentos de propiedad' }, group: { en: 'Property', es: 'Propiedad' }, plain: { en: 'Organize a property-document request for professional review.', es: 'Organizar una solicitud de documentos de propiedad para revisión profesional.' }, keywords: ['title search', 'title review', 'buying a house', 'buy a house', 'purchase deed', 'selling a house', 'property', 'estudio de titulo', 'comprar casa', 'compraventa', 'propiedad', 'escritura'], question: { en: 'Is this a purchase, sale, or document review?', es: '¿Es una compra, venta o revisión de documentos?' }, options: { en: ['Purchase', 'Sale', 'Document review'], es: ['Compra', 'Venta', 'Revisión de documentos'] }, docs: { en: ['Sample property record', 'Sample transaction note'], es: ['Registro de propiedad de ejemplo', 'Nota de transacción de ejemplo'] } },
  { id: 'estate', name: { en: 'Estate intake', es: 'Recepción de asuntos sucesorales' }, group: { en: 'Family & estate', es: 'Familia y sucesiones' }, plain: { en: 'Prepare an estate-related request for a professional.', es: 'Preparar una solicitud sucesoral para un profesional.' }, keywords: ['passed away', 'probate', 'inheritance', 'estate', 'will', 'fallecio', 'fallecimiento', 'herencia', 'sucesion', 'testamento', 'herederos'], question: { en: 'Is a will available?', es: '¿Hay un testamento disponible?' }, options: { en: ['Yes', 'No', 'Not sure'], es: ['Sí', 'No', 'No sé'] }, docs: { en: ['Sample estate record', 'Sample will, if available'], es: ['Registro sucesoral de ejemplo', 'Testamento de ejemplo, si está disponible'] } },
  { id: 'family', name: { en: 'Family consultation', es: 'Consulta de familia' }, group: { en: 'Family & estate', es: 'Familia y sucesiones' }, plain: { en: 'Organize a family-related consultation request.', es: 'Organizar una solicitud de consulta familiar.' }, keywords: ['divorce', 'custody', 'child support', 'separation', 'divorcio', 'custodia', 'pension alimentaria', 'manutencion', 'separacion'], question: { en: 'What is the main topic?', es: '¿Cuál es el tema principal?' }, options: { en: ['Separation', 'Custody', 'Support'], es: ['Separación', 'Custodia', 'Manutención'] }, docs: { en: ['Sample background note'], es: ['Nota de antecedentes de ejemplo'] } },
  { id: 'affidavit', name: { en: 'Affidavit intake', es: 'Recepción de declaraciones juradas' }, group: { en: 'Documents', es: 'Documentos' }, plain: { en: 'Choose a sample statement type for a document request.', es: 'Elegir un tipo de declaración de ejemplo para una solicitud.' }, keywords: ['affidavit', 'sworn statement', 'notarize', 'lost license', 'lost driver license', 'lost drivers license', 'lost my driver license', 'lost my driver s license', 'declaracion jurada', 'juramento', 'notarizar', 'perdi la licencia', 'perdi mi licencia', 'licencia perdida'], question: { en: 'Which statement do you need?', es: '¿Qué tipo de declaración necesita?' }, options: { en: ['Lost license', 'Residence', 'Identity'], es: ['Licencia perdida', 'Residencia', 'Identidad'] }, docs: { en: ['Sample statement draft'], es: ['Borrador de declaración de ejemplo'] } },
  { id: 'employment', name: { en: 'Employment consultation', es: 'Consulta laboral' }, group: { en: 'Work', es: 'Trabajo' }, plain: { en: 'Prepare an employment-related request for professional review.', es: 'Preparar una solicitud laboral para revisión profesional.' }, keywords: ['wrongful termination', 'fired', 'dismissed', 'unpaid wages', 'employment', 'despido', 'despedido', 'salarios', 'laboral', 'empleo'], question: { en: 'What is the main topic?', es: '¿Cuál es el tema principal?' }, options: { en: ['Dismissal', 'Pay', 'Other'], es: ['Despido', 'Pago', 'Otro'] }, docs: { en: ['Sample work-related note'], es: ['Nota laboral de ejemplo'] } },
  { id: 'human', name: { en: 'Team review', es: 'Revisión del equipo' }, group: { en: 'Team', es: 'Equipo' }, plain: { en: 'Prepare a simulated handoff without automated case advice.', es: 'Preparar un relevo simulado sin orientación automática sobre el caso.' }, keywords: ['criminal', 'arrest', 'arrested', 'bail', 'human', 'person', 'talk to someone', 'penal', 'criminal', 'arresto', 'arrestado', 'fianza', 'persona', 'hablar con alguien'], question: { en: 'Team review', es: 'Revisión del equipo' }, options: { en: [], es: [] }, docs: { en: [], es: [] } },
];
export const serviceById = id => SERVICES.find(service => service.id === id) || null;
export const label = (value, lang) => value?.[lang] || value?.en || '';
